### ISSUE TITLE
"Contribution guidelines" link does not work

### ISSUE THREAD

**Issue by sunysaurav** [NIT-dgp/nit-dgp.github.io#12]
![screenshot from 2017-01-25 19-46-50](https://cloud.githubusercontent.com/assets/10153038/22293817/16fcdb54-e337-11e6-919a-094e0465997b.png)

**Comment by ananyo2012** [comment]
Thanks for reporting this. I think you can take this up @sunny5125

**Comment by akshatnitd** [comment]
@ananyo2012 I think this issue is solved and can be closed
