### ISSUE TITLE
Link to github repo not working

### ISSUE THREAD

**Issue by abh3po** [NIT-dgp/nit-dgp.github.io#19]

**Comment by naveenkumarsangi** [comment]
Some elaboration required @abhsag24 !?

**Comment by abh3po** [comment]
@nkprince007 clicking on the link to our github repo we get redirected to the sites homepage, i checked the code to see that the link is correct :( can you reproduce?

**Comment by naveenkumarsangi** [comment]
I still don't seem to understand.. could you show the exact lines you were talking about?

**Comment by sonalkr132** [comment]
Fixed it b03c5899f23bdef01e5abd86cb7cb4c59330c67a 
![qgixzj4y3twns](https://cloud.githubusercontent.com/assets/7680662/25566995/e9c1fe4c-2e01-11e7-89a4-cec059804905.gif)
