### ISSUE TITLE
GSoC_Heat.md: Fsearch:Add Download all button to ftp sites

### ISSUE THREAD

**Issue by jainsahil1997** [NIT-dgp/nit-dgp.github.io#6]
The link provided for the issue Add Download all button to ftp sites under Fearch is linked to https://github.com/NIT-dgp/chrome-search-extension/issues/36  
instead of
https://github.com/NIT-dgp/chrome-search-extension/issue/61

**Comment by naveenkumarsangi** [comment]
Issue fixed in https://github.com/NIT-dgp/nit-dgp.github.io/commit/841524d3d1095674681d34261be08508f421b37b
